### ISSUE TITLE
Async updates sometimes hang

### ISSUE THREAD

**Issue by jamescodesthings** [maximbaz/spaceship-prompt#14]
**Current behavior**

Sometimes after using iterm2 and zsh for a few minutes the async updates will hang.

This leads to something that looks like this:
![image](https://user-images.githubusercontent.com/32203362/64005430-55225100-cb08-11e9-8254-5f91e6a80007.png)

Where it should look like this:
![image](https://user-images.githubusercontent.com/32203362/64005439-5b183200-cb08-11e9-8fd7-20a6a28c270b.png)

Resetting the shell seems to be the only way to recover. Not sure if you've seen this before?

**Expected behavior**

It should look like the second screenshot.

#### Relevant Zsh configuration (`.zshrc`)
Config:
```zsh
export SPACESHIP_AWS_SYMBOL="☁️  "
export SPACESHIP_DIR_TRUNC=0 # Default is 3

if is-iterm; then
  export SPACESHIP_PROMPT_ADD_NEWLINE=false
  export SPACESHIP_CHAR_SYMBOL="> "
fi
```
is-iterm (just for completeness).
```zsh
#!/usr/bin/env zsh

function is-iterm() {
  is equal "$TERM_PROGRAM" "iTerm.app"
}

is-iterm "$@"
```
Load using zplugin
```zsh
zplugin load maximbaz/spaceship-prompt
```

#### Environment

**Spaceship version:** 3.4.1
**Zsh version:** zsh 5.7.1 (x86_64-apple-darwin18.2.0)
**Zsh framework:** None
**Zsh plugin manager:** zplugin (https://github.com/zdharma/zplugin)
**Terminal emulator:** Iterm2 Build 3.3.2
**Operating system:** 
      System Version: macOS 10.14.6 (18G95)
      Kernel Version: Darwin 18.7.0

#### Screenshot
See Above
**Possible solution**
Have only fixed by restarting iTerm/zsh.

**Comment by jamescodesthings** [comment]
Note: Also using nodenv and rbenv which are lazily loaded using https://github.com/qoomon/zsh-lazyload:

```zsh
#!/usr/bin/env zsh

node_globals=(
  npm
  node
  ${(f)"$(cat $HOME/.nodenv/default-packages)"}
  fix-subs
  sls
)

lazyload 'eval "$(nodenv init -)"' nodenv ${node_globals}
lazyload 'eval "$(pyenv init -)"' pyenv python aws-mfa
lazyload 'eval "$(rbenv init -)"' rbenv ruby scss-lint
lazyload 'eval "$(jenv init -)"' jenv java javac
lazyload 'eval "$(pipenv --completion)"' pip pipenv
```

**Comment by max-baz** [comment]
I have seen this a few times, very annoying! Haven't actually looked into how to resolve it, if you feel passionate, help is very welcome 😉

**Comment by max-baz** [comment]
I've started to experience this issue more and more often, very annoying :( Will try to rebase on latest upstream/master as well as update zsh-async locally and see if it gets any better...

**Comment by camsteffen** [comment]
Maybe this is related to the pure prompt issue where git stops updating? See https://github.com/sindresorhus/pure/issues/455#issuecomment-555198254.

**Comment by max-baz** [comment]
I have switched to [powerlevel10k](https://github.com/romkatv/powerlevel10k) some time ago, it's actively maintained and achieves very nice performance without using zsh-async, I highly recommend you to check it out as well.

If you want to have something for reference to start with, you can find my personal config in my [dotfiles](https://github.com/maximbaz/dotfiles/blob/master/.zsh/prompt.zsh).

I'm not planning to maintain this fork anymore, so I'll close this issue.

Thanks for reporting and all your comments!
