### ISSUE TITLE
spaceship::exists behaviour when async being used

### ISSUE THREAD

**Issue by coredump** [maximbaz/spaceship-prompt#2]
**Current behavior**

For some reason, when converting the node section to async, I found out that `spaceship::exists` missbehaves and won't find any of the binaries. What is weirder is that I did it the same way than I did with the ruby section, and it works fine on ruby. I think it may be some order of execution problem. 

In the end, all of the exist checks return `1` and the section isn't shown (no node version can be found).
I added the section to this gist in case anyone wants to take a look: https://gist.github.com/coredump/ac24a646528d0cacfd40531d5e41df1c

**Expected behavior**
node version information would show up as ruby does.

I am using spaceship with oh-my-zsh, if that makes any difference.

**Comment by max-baz** [comment]
Hmmm, weird, I also copy-pasted your gist and it works for me 🤔 Could I ask you to try to investigate more, since you can reproduce it? What happens for example, if you inline the `spaceship::exists` and use `command -v XXX > /dev/null 2>&1` directly, still an issue? I'm wondering where the problem might be, in sourcing lib/utils.zsh or somewhere else.

**Comment by coredump** [comment]
So, order of initialization I guess? My NVM stuff was initializing on a file in the end of `~/.zshrc`, so after the theme stuff was loaded. On a hunch a moved it to before and now it works.
Weird because my rbenv stuff was ALSO on the bottom but the `command -v` worked fine. I guess the nvm people must be doing some weird init that is different.

**Comment by max-baz** [comment]
I wonder if you move your nvm stuff back to the end of the `~/.zshrc`, will you again reproduce the issue or not? If not, this could mean it was a weird caching problem. If yes, can you tell me what kind of nvm stuff is it?

**Comment by max-baz** [comment]
#13 has "node" section migrated, and $PATH is being propagated now to async worker, so _should work_ — let me know if there are still some issues.
