### ISSUE TITLE
Vi mode indicator doesn't update

### ISSUE THREAD

**Issue by coredump** [maximbaz/spaceship-prompt#4]
**Current behavior**

When using vi mode on zsh, the mode indicator doesn't change to reflect the current mode (insert or normal).

This is happening with the unmodified vi mode indicator, non async, so there may be somerhing related to the async stuff put in place.

**Expected behavior**

Pressing your mode change key (ESC by default) should update the vi mode indicator.

**Comment by coredump** [comment]
So I did some debugging and I think this has to do with the `$KEYMAP` variable not being defined or available to the `vi_mode` section. It is definitely something related to the async initialization code, because if I add the section to `RPROMPT` it updates fine.

I cound't find a place where the variable is available and/or passable to the async part yet.

**Comment by max-baz** [comment]
I confirm, unfortunately I have no idea either where that variable should come from 😕

**Comment by coredump** [comment]
It's populated automatically by zsh, I just don't know what part of the async code  can see it to pass it forward.

**Comment by coredump** [comment]
Found a fix, very simple thing. Just need to do this on the vim mode:

```
spaceship_vi_mode_enable() {
  function zle-keymap-select() { PROMPT=$(spaceship::compose_prompt $SPACESHIP_PROMPT_ORDER); zle reset-prompt ; zle -R }
  zle -N zle-keymap-select
  bindkey -v
}
```
And make sure you initialize your shell with the `spaceship_vi_mode_enable` after something that changes the `zle-keymap-select` function, like OMZ vi-mode plugin.

**Comment by max-baz** [comment]
> And make sure you initialize your shell with the spaceship_vi_mode_enable after something that changes the zle-keymap-select function, like OMZ vi-mode plugin.

Is this new comparing to the non-async version? I am not using vi mode so I maybe don't know something, but ideally we need to find a solution that doesn't require users changing their configuration.

Can we execute these 3 lines once during setup, in [spaceship.zsh](https://github.com/maximbaz/spaceship-prompt/blob/c140e4405b9eac5811f66fb1ade3bc562be519cf/spaceship.zsh#L183) for example?

**Comment by coredump** [comment]
I think that doesn't work because the vi mode section reinitializes the function/zle settings. I tried on some places around the code and it didn't work at all.

**Comment by coredump** [comment]
Actually:

```
  test -f Gemfile || test -f Rakefile || test -f "(../)#.ruby-version" || test -n *.rb(#qN^/) || return
```
the test -f `ruby_version` thing doesn't seem to work (because I think that's interpreted as a string), it also can spiral out of control because there's no limit on how far the check will go up.

Second test (the one for *.rb files) fails because `-n` checks a string and that generates a list of files, so it actually hides ruby on directories with .rb files on it. What is weird, i know, because that's used on my test too, but it may be related to using test instead of [[ or something. Or maybe mine is wrong too and I just didn't see it happening.

**Comment by max-baz** [comment]
Thanks for sharing the findings about the ruby section, I already pinged @cyrinux to have a look 😉 

I don't feel comfortable with the proposed way to handle `vi` section, feels wrong that now there is a new setup step. I'll keep this ticket open in case someone wants to find another solution.

**Comment by cyrinux** [comment]
Hi guys, ruby_version check works for me, this is what is use for a project. Will give an eye.

**Comment by max-baz** [comment]
I have switched to [powerlevel10k](https://github.com/romkatv/powerlevel10k) some time ago, it's actively maintained and achieves very nice performance without using zsh-async, I highly recommend you to check it out as well.

If you want to have something for reference to start with, you can find my personal config in my [dotfiles](https://github.com/maximbaz/dotfiles/blob/master/.zsh/prompt.zsh).

I'm not planning to maintain this fork anymore, so I'll close this issue.

Thanks for reporting and all your comments!
