### ISSUE TITLE
Prompt does not show up if $SPACESHIP_ROOT is not set correctly

### ISSUE THREAD

**Issue by cole-h** [maximbaz/spaceship-prompt#9]
EDIT: As I noted in the thread below, if your `$SPACESHIP_ROOT` is not set to maximbaz's repo in your plugin manager's setup, the prompt won't display correctly (or at all). Just `unset SPACESHIP_ROOT` and source your zshrc and it should work.

---

**Current behavior**

When I add `zgen load maximbaz/spaceship-prompt spaceship` to my zgen-plugins file and reload it, zgen clones your repo, but spits out an error that says `zsh: spaceship_precmd_hook: function definition file not found`

**Expected behavior**

After adding the load line to the zgen-plugins file and reloading everything, the prompt should display. Instead, it shows the default prompt.

#### Relevant Zsh configuration (`.zshrc`)

```zsh
zgen load mafredri/zsh-async
zgen load maximbaz/spaceship-prompt spaceship
```

#### Environment

**Spaceship version:** 3.4.1
**Zsh version:** zsh 5.5.1
**Zsh framework:** oh-my-zsh (through zgen)
**Zsh plugin manager:** zgen
**Terminal emulator:** WSLtty
**Operating system:** Windows 10 (but the environment is set up as Arch)

#### Screenshot

Top portion is when using your async spaceship; very last lines is using the main repo.

![screenshot](https://i.imgur.com/wnXEWSK.png)

I just recently started using zsh again, so it is entirely possible this is user error.

**Comment by max-baz** [comment]
Hmmm, the first error I see on your screenshot is `command not found: async_init`, which is part of `zsh-async`. I wonder if zgen doesn't load that module, or tries to load spaceship before loading zsh-async...

`spaceship_precmd_hook` is defined right here, so I'm not sure why zgen doesn't load it.

https://github.com/maximbaz/spaceship-prompt/blob/360e989d8463a512273eb7e120d5607f10e57fb8/lib/hooks.zsh#L17

I can only tell you that this works with antigen 🙂

**Comment by max-baz** [comment]
Also check, maybe this PR broke zgen support: https://github.com/mafredri/zsh-async/pull/23

**Comment by cole-h** [comment]
That is the weirdest thing to me. Maybe zgen has some kind of cache and main spaceship is interfering with this version? Only thing I can think of.

I also tried symlinking `async.zsh` to `async.plugin.zsh` to no avail.

Do you think it'd be fine to mix antigen with zgen? Until I can figure out why this is happening, I might as well do that.

**Comment by max-baz** [comment]
Cache is a very good idea, could be! Antigen stores everything in `~/.antigen`, so removing that folder is a brutal (but efficient) way to clear the cache. Maybe you have `~/.zgen` which you can purge? 🙂 

I don't think mixing antigen with zgen will work, I noticed antigen is merging all zsh configs and modules in one big file and then precompiling it, for faster prompt loading.

**Comment by cole-h** [comment]
Okay, it seems it _was_ a problem with installing the original Spaceship theme -- the `$SPACESHIP_ROOT` var was set to denysdovhan's repo. Unsetting and reinstalling your prompt fixes the problem, and this works now!

I only have a few issues with the actual prompt now: 

1) `SPACESHIP_RPROMPT_ORDER` seems to be broken. I use the RPROMPT for git status and git branch; it works when in the normal PROMPT, but not on RPROMPT ![screenshot](https://i.imgur.com/QlsYtHZ.png)
2) exec_time also seems to be broken on both RPROMPT and normal PROMPT

I can file separate issues for these if you like.

**Comment by max-baz** [comment]
`exec_time` definitely works for me:

![image](https://user-images.githubusercontent.com/1177900/43851853-175cc546-9b3c-11e8-853f-9bfbd32bec7d.png)

As for `SPACESHIP_RPROMPT_ORDER`, sure, feel free to create a new issue. A fair warning though, I won't be looking into it, because I'm not using this feature and it doesn't seem like upstream will be ready to merge async any time soon. A PR is welcome, if you make one, I'll do my best to review and merge it fast.

**Comment by cole-h** [comment]
Alright, got `exec_time` working: the second after I checked the value of `$SPACESHIP_EXEC_TIME_SHOW`, it decided to pop back up. I'm gonna go ahead and close this issue and submit the RPROMPT one in a few. Then I'll familiarize myself with the codebase and try to fix that. Thanks for the help!
